# Generated by Django 6.0.6 on 2026-06-10 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('summary', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='issue_tracker.statusmodel')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='issue_tracker.typemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
