# Generated by Django 6.0.6 on 2026-06-11 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0002_issuemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuemodel',
            name='type_old',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='issue_tracker.typemodel'),
        ),
        migrations.RemoveField(
            model_name='issuemodel',
            name='type',
        ),
        migrations.AddField(
            model_name='issuemodel',
            name='type',
            field=models.ManyToManyField(related_name='issues', to='issue_tracker.typemodel'),
        ),
    ]
