# Generated by Django 6.0.6 on 2026-06-11 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0004_transfer_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuemodel',
            name='type_old',
        ),
    ]
