# Generated by Django 6.0.5 on 2026-06-22 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0008_make_project_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuemodel',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issue_tracker.projectmodel'),
        ),
    ]
