# Generated by Django 6.0.5 on 2026-06-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0009_alter_issuemodel_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuemodel',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
